env:
  browser: true
  es2021: true
extends:
  - airbnb-base
  # - airbnb-typescript/base
  # - plugin:@typescript-eslint/recommended
overrides: []
# parser: '@typescript-eslint/parser'
# parserOptions:
  # project: ./tsconfig.json
  # ecmaVersion: latest
  # sourceType: module
# plugins:
#   - '@typescript-eslint'
rules:
  no-console: off
  max-len: 1
  # import/prefer-default-export: 1
  no-plusplus: off
  prefer-destructuring: 1
  import/no-cycle: 1
  implicit-arrow-linebreak: 1
  no-underscore-dangle: off
  no-func-assign: off
  no-unused-vars: 1
  no-param-reassign: off
  consistent-return: off
  no-restricted-syntax: off
  guard-for-in: off
  no-await-in-loop: off
  # TODO: Remove this after we have tests
  no-nested-ternary: 1 