name: "Auto eslint formatter"
description: "Format JS code with EsLint & leave comments"
author: "Johan Ekman"

inputs:
  auto_fix:
    description: "Auto fixes certain errors/warnings"
    required: false
    default: "false"
  path:
    description: "the path for the lint"
    required: false
    default: "src/"
  token:
    description: "Token used for comments"
    required: true
  comment:
    description: "Leave comments on the PR"
    required: false
    default: "false"
  extension:
    description: "The file extension that should be targeted by the linter"
    required: false
    default: "ts"
    
runs:
  using: node16
  main: lib/index.js
