name: Testing action
on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm install
      - name: build
        run: npm run build
      - name: GIT Commit Build Artifacts (coverage, dist, devdist, docs)
        run: |
          git config --global user.name "build"
          git config --global user.email "username@users.noreply.github.com"
          git commit -a -m "New build"
          git push